//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_AOwn
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Donar
    {
       
        public int ID { get; set; }
        [Required(ErrorMessage = "Enter your name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Enter your Phone number")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Enter your a valid email")]
        [EmailAddress]
        public string Email { get; set; }
        [Required(ErrorMessage = "Enter donation amount")]
        [Range(100,10000000000000000000, ErrorMessage ="Minimum donation is 100 Taka")]
        public int Amount { get; set; }
        [Required(ErrorMessage = "Enter your address")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Give some well wishes")]
        public string Comment { get; set; }
    }
}
