//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_AOwn
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Receiver
    {
        public int ID { get; set; }
        [Required, Display(Name = "Enter your name")]
        public string Name { get; set; }
        [Required, Display(Name = "Enter your phone number")]
        public string Phone { get; set; }
        [Required, Display(Name = "Enter correct amount")]
        [Range(0,15000,ErrorMessage ="Exceeded maximum amount")]
        public int RAmount { get; set; }
        [Required(ErrorMessage ="Tell your current situation")]
        public string Comment { get; set; }
    }
}
